name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run tests
      run: |
        python -m pytest app/test_main.py

    - name: Build Docker image
      run: docker build -t dineshvaishnav/ci-cd-pipeline:latest .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push dineshvaishnav/ci-cd-pipeline:latest

